# Generated by Django 2.2.2 on 2019-12-14 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_seen_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
