# Generated by Django 2.2.2 on 2019-12-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0005_auto_20191215_0534'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_registered_user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='random_coffee_bot_telegram_username',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('telegram_id',), name='unique_registered_user'),
        ),
    ]
