# Generated by Django 2.2.2 on 2019-12-15 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0006_auto_20191215_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='sent_user_a_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='sent_user_b_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('I', 'Сам на себя'), ('T', 'В компании')], max_length=100),
        ),
    ]
