# Generated by Django 2.2.2 on 2019-12-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0008_auto_20191215_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='state_saved',
        ),
        migrations.AddField(
            model_name='user',
            name='state_context_saved',
            field=models.CharField(default="{'name': 'NullState', 'params': {}}", max_length=500),
        ),
    ]
