# Generated by Django 2.2.2 on 2019-12-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0011_auto_20191218_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='user_a_meeting_failure_reason',
            field=models.CharField(choices=[('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_b_meeting_failure_reason',
            field=models.CharField(choices=[('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userstate',
            name='context',
            field=models.CharField(default="{'state_name': 'NullState', 'params': {}}", max_length=500),
        ),
    ]
