# Generated by Django 2.2.2 on 2019-12-18 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0012_auto_20191218_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='first_time_sent_at',
        ),
        migrations.AlterField(
            model_name='invitation',
            name='cancel_reason',
            field=models.CharField(choices=[('NT', 'Вряд ли найду время'), ('NIM', 'Не в настроении'), ('NI', 'Что-то неинтересно...')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='message_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
