# Generated by Django 2.2.2 on 2019-12-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0013_auto_20191218_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='cancel_reason',
            field=models.CharField(choices=[('', '-'), ('NT', 'Вряд ли найду время'), ('NIM', 'Не в настроении'), ('NI', 'Что-то неинтересно...')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_a_meeting_failure_reason',
            field=models.CharField(choices=[('', '-'), ('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_b_meeting_failure_reason',
            field=models.CharField(choices=[('', '-'), ('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], max_length=100, null=True),
        ),
    ]
