# Generated by Django 2.2.2 on 2019-12-18 01:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0014_auto_20191218_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='cancel_reason',
            field=models.CharField(blank=True, choices=[('', '-'), ('NT', 'Вряд ли найду время'), ('NIM', 'Не в настроении'), ('NI', 'Что-то неинтересно...')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_a_meeting_failure_reason',
            field=models.CharField(blank=True, choices=[('', '-'), ('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='user_b_meeting_failure_reason',
            field=models.CharField(blank=True, choices=[('', '-'), ('DC', 'Партнер не вышел на связь'), ('CA', 'Не смогли договориться когда/где'), ('FM', 'Форс-мажор')], default='', max_length=100),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.BooleanField(null=True)),
                ('message_id', models.CharField(max_length=100, null=True)),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connector.User')),
            ],
        ),
    ]
