# Generated by Django 2.2.2 on 2019-12-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0015_auto_20191218_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='callback_data',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='direction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
