# Generated by Django 2.2.2 on 2019-12-18 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0016_auto_20191218_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='callback_data',
        ),
    ]
