# Generated by Django 2.2.2 on 2019-12-18 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connector', '0018_auto_20191218_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='sent_at',
            new_name='broadcasted_at',
        ),
    ]
